### ISSUE TITLE
Parse types better

### ISSUE THREAD

**Issue by mastfissh** [davidpdrsn/diesel-factories#10]
Currently we rely on treating types as strings, and doing string operations to de-structure them into the correct form. I think it would be better to try to correct parse the types into their components.

I think having robust logic to support queries like
```rust
optional = parsed_ident.outer_type_is("Option")
if optional {
  inside_type_name = parsed_ident.types().unwrap().type_name()
  return inside_type_name == "Association"
}
```
Have to figure out the best API to access this information, but I think this interface will be a lot less brittle than the current regex approach.

Related to https://github.com/davidpdrsn/diesel-factories/issues/8 .

**Comment by davidpdrsn** [comment]
Totally. We should probably get more familiar with the syn crate and what it can do. Might be also be nice to find other crates and see what they do. [derive_builder](https://crates.io/crates/derive_builder) and [structopt](structopt = "0.2.15") comes to mind.
