### ISSUE TITLE
Document how to use auto-generated associations

### ISSUE THREAD

**Issue by mastfissh** [davidpdrsn/diesel-factories#16]
Diesel factories has a rather nice property where if there's a non-optional association, it'll ensure that they're created.

But if you want to access these, it's not so clear how to.

It'd be good to add an example of accessing an association that was populated by using a factory (ass opposed to instantiated beforehand).

**Comment by davidpdrsn** [comment]
To find associations that are created implicitly you have to write SQL queries. There is an example of how to do that here https://github.com/davidpdrsn/diesel-factories
