### ISSUE TITLE
Multiple Connection Types

### ISSUE THREAD

**Issue by bytebuddha** [davidpdrsn/diesel-factories#19]
I'm currently working on a program that needs to work for both the Sqlite and Pg diesel backends. I would like to use this crate for testing on both but the Factory trait specifies the diesel connection to use statically. Is there any way possible to use this crate with multiple backends?

I've attempted to Consolidate both backends into a new struct called DatabaseBackends and implementing Connection on it but all the Type parameters required for the Connection trait make this almost impossible without recreated a lot of types.

**Comment by davidpdrsn** [comment]
That sounds interesting. I haven't had that use case myself.

Would you be able to try and implement the Factory trait manually (without using the macro) and see if it is possible using the current API? If it does we can look at how to improve the macro to support this use case.

I suspect Factory::Connection would have to be a generic that implements Diesels connection trait. 

You could possibly use https://github.com/dtolnay/cargo-expand and modify the output of the macro to get a good starting point.

**Comment by bytebuddha** [comment]
I've found this earlier today https://github.com/diesel-rs/diesel/issues/882#issuecomment-300257476 and I've come to the conclusion that this is ultimately to much work for the result.

I'm going to close this as now this seems a bit out of scope for this library, it seem's to me the best place for a future generic connection would most likely be in it's own crate.
