### ISSUE TITLE
proc-macro derive panicked: Expected a TypePath here

### ISSUE THREAD

**Issue by LucasPickering** [davidpdrsn/diesel-factories#20]
Hello! I'm trying to start using this crate but having trouble with my first factory. I'm trying to use it from an integration test, which means my model is in a library crate then my factory exists in a separate crate. Here's what my model looks like:

```
#[derive(Clone, Debug, PartialEq, Identifiable, Queryable)]
#[table_name = "hardware_specs"]
pub struct HardwareSpec {
    pub id: Uuid,
    pub slug: String,
    pub name: String,
    pub num_registers: i32,
    pub num_stacks: i32,
    pub max_stack_length: i32,
}
```

and here's my factory:

```
use diesel_factories::Factory;

#[derive(Clone, Factory)]
#[factory(
    model = "gdlk_api::models::HardwareSpec",
    table = "gdlk_api::schema::hardware_specs"
)]
pub struct HardwareSpecFactory<'a> {
    pub slug: &'a str,
    pub name: &'a str,
    pub num_registers: i32,
    pub num_stacks: i32,
    pub max_stack_length: i32,
}
```

But with this code I get an error on the derive macro saying 

```
proc-macro derive panicked
message: Expected a TypePath here
```

I've tried moving several things around, including importing one/both types (the model and the table) locally then using just the local path, but got the same result. I know I'll also need to include `id = "uuid::Uuid"` because of my primary key type, but that gives a different error so I decided to try to resolve this one first.

So my question is, am I doing something obviously wrong? If it's not clear what's going on, I can put together a minimal reproduction but I wanted to check if there was an obvious solution first. Thank you!

**Comment by davidpdrsn** [comment]
Sorry for the poor error message. This happens because factories cannot contain borrows, namely the `'a` in `HardwareSpecFactory<'a>`. So you have to change it to

```rust
#[derive(Clone, Factory)]
#[factory(
    model = "gdlk_api::models::HardwareSpec",
    table = "gdlk_api::schema::hardware_specs"
)]
pub struct HardwareSpecFactory {
    pub slug: String,
    pub name: String,
    pub num_registers: i32,
    pub num_stacks: i32,
    pub max_stack_length: i32,
}
```

Afaik there is no fundamental reason lifetimes aren't allowed so could be fixed. I'll open a separate issue for that.

**Comment by LucasPickering** [comment]
@davidpdrsn Thank you! that fixed it
